#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🤖 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '🤢 Your styling doesnt look soo good.
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo '😤 ESLint Check Failed.
                Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡 Failed Type check.
            Make the changes required above.'
    false;
)

# If everything passes... we try to build
echo '🤖 ...Code looks good to me... Trying to build now. 🏗️'

npm run build ||
(
    echo '❌🔨❌ Looks like your build failed ❌🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Everything looks good! I am committing this now. ✅✅✅✅'